name: Build and Package for All OS with Python 3.12 and Custom Name

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Executable
      run: |
        OS_SUFFIX=""
        if [ "${{ runner.os }}" = "Windows" ]; then
          OS_SUFFIX="-Windows"
        elif [ "${{ runner.os }}" = "Linux" ]; then
          OS_SUFFIX="-Linux"
        elif [ "${{ runner.os }}" = "macOS" ]; then
          OS_SUFFIX="-macOS"
        fi
        pyinstaller --onefile --add-data "app;app" --add-data "UI;UI" --name SwiftDocz$OS_SUFFIX launcher.py

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: SwiftDocz$OS_SUFFIX
        path: dist/SwiftDocz$OS_SUFFIX*

  collect:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create SwiftDocz Directory
      run: mkdir SwiftDocz
    - name: Download All Executables
      uses: actions/download-artifact@v2
      with:
        path: SwiftDocz/
    - name: Upload SwiftDocz Folder
      uses: actions/upload-artifact@v2
      with:
        name: SwiftDocz-Final
        path: SwiftDocz
